package pos.corba;


/**
* hello/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sábado, 18 de Junho de 2016 17h54min56s BRT
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
